// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpJB4G78QBrWrmzvUgkri6_bRO7Jf_Wo',
    appId: '1:741489431528:web:746eef86850d7311080a5d',
    messagingSenderId: '741489431528',
    projectId: 'o2education',
    authDomain: 'o2education.firebaseapp.com',
    storageBucket: 'o2education.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAyXmYmRwkF_RuPSfpOIkQPi7jxvMEeM',
    appId: '1:741489431528:android:61743b9fd3b5196e080a5d',
    messagingSenderId: '741489431528',
    projectId: 'o2education',
    storageBucket: 'o2education.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSW8VzhCGDkcb8AIHicVKk1TJgfJxuZYQ',
    appId: '1:741489431528:ios:10616cf210e6157a080a5d',
    messagingSenderId: '741489431528',
    projectId: 'o2education',
    storageBucket: 'o2education.appspot.com',
    iosBundleId: 'com.example.otwo',
  );

}